FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app
ARG SERVICE
COPY . .
RUN mvn -pl ${SERVICE} -am clean package -DskipTests -q

FROM eclipse-temurin:21-jre
WORKDIR /app
ARG SERVICE
COPY --from=builder /app/${SERVICE}/target/*.jar app.jar
EXPOSE 8080 8081 8082 8083 8084 8090
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
