FROM eclipse-temurin:21-jre
WORKDIR /app
ARG SERVICE
COPY ${SERVICE}/target/*.jar app.jar
EXPOSE 8080 8081 8082 8083 8084 8090
ENTRYPOINT ["java", "-Dnacos.logging.default.config.enabled=false", "-jar", "/app/app.jar"]
