spring:
  datasource:
    url: jdbc:mysql://192.168.31.2:3306/crawler_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: mysql_FxYHD4
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:192.168.31.2:8848}
  rocketmq:
    name-server: ${ROCKETMQ_NAMESRV:192.168.31.2:9876}
  data:
    elasticsearch:
      uris: ${ES_URLS:http://192.168.31.2:9200}
      username: ${ES_USER:elastic}
      password: ${ES_PASSWORD:Elastic_dnw7WH}

minio:
  endpoint: ${MINIO_ENDPOINT:http://192.168.31.2:9000}
  accessKey: ${MINIO_ACCESS:admin}
  secretKey: ${MINIO_SECRET:admin123}
