server:
  port: 8083

spring:
  application:
    name: crawler-search-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:192.168.31.2:8848}
        namespace: ${NACOS_NAMESPACE:public}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:192.168.31.2}:${MYSQL_PORT:3306}/${MYSQL_DB:crawler_platform}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:mysql_FxYHD4}
  data:
    elasticsearch:
      uris: ${ES_URLS:http://192.168.31.2:9200}
      username: ${ES_USER:elastic}
      password: ${ES_PASSWORD:Elastic_dnw7WH}

app:
  es:
    content-index: ${ES_CONTENT_INDEX:spider_content}

minio:
  endpoint: ${MINIO_ENDPOINT:http://192.168.31.2:9000}
  accessKey: ${MINIO_ACCESS:minio_ZzhWQ2}
  secretKey: ${MINIO_SECRET:minio_DhYfdD}
  html-bucket: ${MINIO_HTML_BUCKET:crawler}
  js-bucket: ${MINIO_JS_BUCKET:crawler}

jwt:
  secret: crawler-platform-jwt-secret-key-must-be-long-enough-256
  expire: 7200

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.collect: INFO
